# Generated by Django 4.1.7 on 2023-04-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Silla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_silla', models.IntegerField()),
                ('cantidad_silla', models.IntegerField()),
            ],
        ),
    ]
