# Generated by Django 4.1.7 on 2023-04-05 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_gymmodel_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gymmodel',
            old_name='titulovideo',
            new_name='tituloejercicio',
        ),
    ]
